name: Bot Vagas TI
on:
  schedule:
    # Executa às 9h, 12h, 15h, 18h (horário UTC = 6h, 9h, 12h, 15h Brasília)
    - cron: '0 9,12,15,18 * * *'
  workflow_dispatch:  # Permite executar manualmente

jobs:
  buscar-vagas:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Timeout de 15 minutos
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependências do sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Instalar dependências Python
      run: |
        pip install -r requirements.txt
        
    - name: Executar Bot de Vagas
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        LOCAL: "Salvador, BA"
        MAX_VAGAS_POR_PLATAFORMA: "5"
        TENTATIVAS_BUSCA: "2"
        TIMEOUT_PAGINA: "25"
        INTERVALO_BUSCA_MINUTOS: "180"
        REQUESTS_POR_HORA: "10"
      run: |
        python bot_vagas.py